### ISSUE TITLE
Fact sheet

### ISSUE THREAD

**Issue by badgettrg** [openMetaAnalysis/Prostate-cancer-screening-with-prostate-specific-antigen#7]
@arahal 
- Can you add the reference to the fact sheet that provides the number for harm?
- Should 110 in 1000 and 18 in 1000 both be converted to percentages (11% and 2%)
- What numbers for NNI should we use? I think what we have is good and adding the NNI for our > 3 yr subgroup might add noise to the table.

**Comment by arahal** [comment]
1) I got the number of harms from the USPSTF guidelines which is the second reference.
2) I think it would be better if we convert them to percentages, to keep a consistent reference in the harms and benefits
3) I think if we just keep the table as it is and not adding the NNI would make it clearer

4) In the first section of the table. where is says, other things to consider? 
  - should we rephrase it : In case screening is done, and a cancer is found that has no signs of aggression (low grade), active surveillance would be preferred and treatment avoided ?

**Comment by arahal** [comment]
@badgettrg 

1) I got the number of harms from the USPSTF guidelines which is the second reference.
2) I think it would be better if we convert them to percentages, to keep a consistent reference in the harms and benefits
3) I think if we just keep the table as it is and not adding the NNI would make it clearer

4) In the first section of the table. where is says, other things to consider?

should we rephrase it : In case screening is done, and a cancer is found that has no signs of aggression (low grade), active surveillance would be preferred and treatment avoided ?

**Comment by arahal** [comment]
@badgettrg 

In the second part of the patient facts sheet. should we also include the PLCO trial in the benefits? showing that there was no mortality benefit. In that way we will be showing the patient all the research done?

**Comment by badgettrg** [comment]
We do not believe that trial added useful data, I would not include it only  add clutter.

Bob Badgett

On Apr 18, 2015, at 12:18 PM, arahal <notifications@github.com<mailto:notifications@github.com>> wrote:

@badgettrghttps://github.com/badgettrg

In the second part of the patient facts sheet. should we also include the PLCO trial in the benefits? showing that there was no mortality benefit. In that way we will be showing the patient all the research done?

**Comment by arahal** [comment]
@badgettrg 

In the harms section in the patient handout, would you like to put the numbers/percentages of the USPSTF guidelines or from our summary of findings table table?

**Comment by arahal** [comment]
@badgettrg 
Please disregard last message as summary of findings table do not show harms and only mortality. sorry for that
